### PR TITLE
Evaluator

### PR DESCRIPTION
**Pull request by squidy5**
Restructures the evaluation code according to the new architecture into the evaluator class.
Creates new Notebook explaining the usage of the evaluator object.

### CODE REVIEW

**Comment by fsenf** [comment]
@rudegrass : Thanks for the suggested update. When running the notebooks, I get some minor bugs:


- **minor bug 1: notebook `Application_of_a_pretrained_classifier.ipynb`**
  ```python
  cc.run_prediction_pipeline(create_filelist = True)
  ---------------------------------------------------------------------------
  TypeError                                 Traceback (most recent call last)
  Input In [8], in <cell line: 1>()
  ----> 1 cc.run_prediction_pipeline(create_filelist = True)
  
  File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/cloud_classifier.py:63, in cloud_classifier.run_prediction_pipeline(self, verbose, create_filelist)
       61 self.load_project_data()
       62 if create_filelist:
  ---> 63     self.extract_input_filelist(verbose=verbose)
       65 self.trainer.load_classifier(self.project_path, verbose=verbose)
       66 self.apply_mask(verbose=verbose)
  
  File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/cloud_classifier.py:154, in cloud_classifier.extract_input_filelist(self, verbose)
      147 satFile_pattern = fh.get_filename_pattern(
      148     self.params["sat_file_structure"], self.params["timestamp_length"]
      149 )
      150 labFile_pattern = fh.get_filename_pattern(
      151     self.params["label_file_structure"], self.params["timestamp_length"]
      152 )
  --> 154 input_files = fh.generate_filelist_from_folder(
      155     folder=self.params["input_source_folder"],
      156     satFile_pattern=satFile_pattern,
      157     labFile_pattern=labFile_pattern,
      158     only_sataData=True,
      159 )
      161 self.param_handler.set_filelists(input_files=input_files)
      162 self.param_handler.save_filelists(self.project_path)
  
  TypeError: generate_filelist_from_folder() got an unexpected keyword argument 'only_sataData'
  
  
  ```

- **minor bug 2: notebook `Plotting_of_example_data.ipynb`**
  ```python
  cp.plot_coocurrence_matrix(forest_prediction, orig_file)
  
  ---------------------------------------------------------------------------
  NameError                                 Traceback (most recent call last)
  Input In [9], in <cell line: 1>()
  ----> 1 cp.plot_coocurrence_matrix(forest_prediction, orig_file)
  
  File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/cloud_plotter.py:260, in cloud_plotter.plot_coocurrence_matrix(self, label_file, truth_file, normalize)
      253 label_data = self.get_plotable_data(
      254     data_file=label_file, reduce_to_mask=True, get_coords=False
      255 )
      256 truth_data = self.get_plotable_data(
      257     data_file=truth_file, reduce_to_mask=True, get_coords=False
      258 )
      259 conf.plot_coocurrence_matrix(
  --> 260     label_data, truth_data, normalize=normalize, show=show
      261 )
  
  NameError: name 'show' is not defined
  ```

And third aspect is perhaps missing data on my side: in notebook `Run Evalution.ipynb` I get:
  ```python
  ev1.create_split_trainingset(eval_size=24, timesensitive=True)
  
  ---------------------------------------------------------------------------
  FileNotFoundError                         Traceback (most recent call last)
  Input In [5], in <cell line: 1>()
  ----> 1 ev1.create_split_trainingset(eval_size=24, timesensitive=True)
  
  File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/evaluator.py:38, in evaluator.create_split_trainingset(self, eval_size, timesensitive)
       32 satFile_pattern = fh.get_filename_pattern(
       33     self.params["sat_file_structure"], self.params["timestamp_length"]
       34 )
       35 labFile_pattern = fh.get_filename_pattern(
       36     self.params["label_file_structure"], self.params["timestamp_length"]
       37 )
  ---> 38 datasets = fh.generate_filelist_from_folder(
       39     self.params["data_source_folder"], satFile_pattern, labFile_pattern
       40 )
       42 training_sets, evaluation_sets, timestamps = fh.split_sets(
       43     datasets, satFile_pattern, eval_size=eval_size, timesensitive=timesensitive
       44 )
       46 self.param_handler.set_filelists(
       47     training_sets=training_sets,
       48     evaluation_sets=evaluation_sets,
       49     input_files=[s[0] for s in evaluation_sets],
       50     eval_timestamps=timestamps,
       51 )
  
  File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/tools/file_handling.py:72, in generate_filelist_from_folder(folder, satFile_pattern, labFile_pattern, only_satData)
       69     return
       71 sat_files, lab_files = {}, {}
  ---> 72 files = os.listdir(folder)
       74 if only_satData:
       75     # return onky satelite date
       76     for file in files:
  
  FileNotFoundError: [Errno 2] No such file or directory: '../data/full_dataset'
  ```
  
**Which additional data are needed to run the evaluator notebook?**

**Comment by squidy5** [comment]
Bugs should be fixed now.
For the data aspect, my data folder looks like this.
data/
  ├── auxilary_files
  ├── example_data
  └── full_dataset

full_dataset contains the complete data set with all sat data and labels. You can either mimic the file structure, or set the `data_source_folder` parameter of the used projects in the notebook. 
This can be either done manually by navigating into the project folder and changing the entry in `data_structure.json` file or via the `ev1.set_parameters(data_source_folder = X)` command inside the notebook.

**Comment by fsenf** [comment]
@rudegrass : Great, minor bugs are fixed now!

However, I still try to find out how evaluation data source needs to be specified. I get this error:

```python
ll ../data/evaluation_data/

insgesamt 1025140
-rw-r--r--. 1 senf 15680198  4. Jun 2021  msevi-medi-20190107_1200.nc
-rw-r--r--. 1 senf 15888603  4. Jun 2021  msevi-medi-20190120_0500.nc
...
-rw-r--r--. 1 senf   213295  4. Jun 2021  nwcsaf_msevi-medi-20201205_0900.nc
-rw-r--r--. 1 senf   249865  4. Jun 2021  nwcsaf_msevi-medi-20201216_1500.nc

ev1.set_project_parameters(data_source_folder = '../data/evaluation_data/' )

ev1.create_split_trainingset(eval_size=24, timesensitive=True, )

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [21], in <cell line: 2>()
      1 ev1.set_project_parameters(data_source_folder = '../data/evaluation_data/' )
----> 2 ev1.create_split_trainingset(eval_size=24, timesensitive=True, )

File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/evaluator.py:42, in evaluator.create_split_trainingset(self, eval_size, timesensitive)
     35 labFile_pattern = fh.get_filename_pattern(
     36     self.params["label_file_structure"], self.params["timestamp_length"]
     37 )
     38 datasets = fh.generate_filelist_from_folder(
     39     self.params["data_source_folder"], satFile_pattern, labFile_pattern
     40 )
---> 42 training_sets, evaluation_sets, timestamps = fh.split_sets(
     43     datasets, satFile_pattern, eval_size=eval_size, timesensitive=timesensitive
     44 )
     46 self.param_handler.set_filelists(
     47     training_sets=training_sets,
     48     evaluation_sets=evaluation_sets,
     49     input_files=[s[0] for s in evaluation_sets],
     50     eval_timestamps=timestamps,
     51 )
     53 self.param_handler.save_filelists(self.project_path)

File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/tools/file_handling.py:121, in split_sets(dataset, satFile_pattern, eval_size, timesensitive)
    119     n = int(eval_size / 24)
    120     for h in range(24):
--> 121         eval_indeces += random.sample(timesorted[h], n)
    122 else:
    123     eval_indeces = random.sample(range(len(dataset)), eval_size)

File ~/.miniconda3/envs/python38/lib/python3.8/random.py:363, in Random.sample(self, population, k)
    361 n = len(population)
    362 if not 0 <= k <= n:
--> 363     raise ValueError("Sample larger than population or is negative")
    364 result = [None] * k
    365 setsize = 21        # size of a small set minus size of an empty list

ValueError: Sample larger than population or is negative


```

**Comment by squidy5** [comment]
How many sets of data are in the `evaluation_data` folder? 
And are there sets for every hour of the day?  My guess is that for some hours of the day no data is found, and therefore no sample can be taken. 
If that is the case I could add a safeguard that makes sure the correct amount of data is actually present!

**Comment by fsenf** [comment]
Yes, it runs when all data are provided. Nice!

We cannot provide such large sample dataset to other users ... Anyway, the material as such might provide valuable content to others even if it cannot be executed without the data ..

Great!

**Comment by fsenf** [comment]
Oh no, too fast! There is still an error later on:

```python
ev1.create_evaluation_data()

ev2.create_evaluation_data()

Trainig evaluation classifier
Masked indices set!
sampling took 123.15815901756287 seconds
Removed 1460 vectors for containig 'Nan' values
Training data created!
Training Tree Classifier
Classifier trained!
Classifier saved!
Prediciting evaluation labels
Classifier loaded!
Masked indices set!
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20200330_0000_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20190402_0100_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20190517_0200_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20200101_0300_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20190406_0400_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20190722_0500_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20200421_0600_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20200223_0700_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20200529_0800_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20190509_0900_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20191030_1000_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20200415_1100_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20190610_1200_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20191229_1300_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20191224_1400_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20200128_1500_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20191220_1600_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20200407_1700_predicted.nc
Input vectors created!
Labels saved as nwcsaf_msevi-medi-20201102_1800_predicted.nc
Removed 220222 vectors for containig 'Nan' values
Input vectors created!

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [7], in <cell line: 1>()
----> 1 ev1.create_evaluation_data()
      2 ev2.create_evaluation_data()

File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/evaluator.py:60, in evaluator.create_evaluation_data(self)
     58 self.cloud_class.run_training_pipeline(create_filelist=False)
     59 print("Prediciting evaluation labels")
---> 60 self.cloud_class.run_prediction_pipeline(create_filelist=False)

File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/cloud_classifier.py:90, in cloud_classifier.run_prediction_pipeline(self, verbose, create_filelist)
     87     labels = [li[i] for i in np.argmax(probas, axis=1)]
     88 # else get only labels
     89 else:
---> 90     labels = self.trainer.predict_labels(vectors, self.params)
     92 filename = self.write_labels(labels, indices, file, probas, verbose=verbose)
     93 label_files.append(filename)

File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/cloud_trainer.py:63, in cloud_trainer.predict_labels(self, vectors, params)
     60 if params["feature_preselection"] and not (self.feat_select is None):
     61     vectors = self.apply_feature_selection(vectors)
---> 63 return self.classifier.predict(vectors)

File ~/.miniconda3/envs/python38/lib/python3.8/site-packages/sklearn/utils/metaestimators.py:113, in _AvailableIfDescriptor.__get__.<locals>.<lambda>(*args, **kwargs)
    110         raise attr_err
    112     # lambda, but not partial, allows help() to work with update_wrapper
--> 113     out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)  # noqa
    114 else:
    116     def fn(*args, **kwargs):

File ~/.miniconda3/envs/python38/lib/python3.8/site-packages/sklearn/pipeline.py:469, in Pipeline.predict(self, X, **predict_params)
    467 Xt = X
    468 for _, name, transform in self._iter(with_final=False):
--> 469     Xt = transform.transform(Xt)
    470 return self.steps[-1][1].predict(Xt, **predict_params)

File ~/.miniconda3/envs/python38/lib/python3.8/site-packages/sklearn/preprocessing/_data.py:973, in StandardScaler.transform(self, X, copy)
    970 check_is_fitted(self)
    972 copy = copy if copy is not None else self.copy
--> 973 X = self._validate_data(
    974     X,
    975     reset=False,
    976     accept_sparse="csr",
    977     copy=copy,
    978     estimator=self,
    979     dtype=FLOAT_DTYPES,
    980     force_all_finite="allow-nan",
    981 )
    983 if sparse.issparse(X):
    984     if self.with_mean:

File ~/.miniconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:566, in BaseEstimator._validate_data(self, X, y, reset, validate_separately, **check_params)
    564     raise ValueError("Validation should be done on X, y or both.")
    565 elif not no_val_X and no_val_y:
--> 566     X = check_array(X, **check_params)
    567     out = X
    568 elif no_val_X and not no_val_y:

File ~/.miniconda3/envs/python38/lib/python3.8/site-packages/sklearn/utils/validation.py:769, in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    767     # If input is 1D raise error
    768     if array.ndim == 1:
--> 769         raise ValueError(
    770             "Expected 2D array, got 1D array instead:\narray={}.\n"
    771             "Reshape your data either using array.reshape(-1, 1) if "
    772             "your data has a single feature or array.reshape(1, -1) "
    773             "if it contains a single sample.".format(array)
    774         )
    776 # make sure we actually converted to numeric:
    777 if dtype_numeric and array.dtype.kind in "OUSV":

ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.


```


**too many nans in the data?**

**Comment by squidy5** [comment]
Looks like actually all vectors from that dataset contained nan-values, and were removed resulting in an empty array.
I think it would be better if the program detects those cases and doesn't terminate, but gives a message instead.
I can add a safeguard to catch those cases

Jun 3, 2022 17:42:37 fsenf ***@***.***>:

**Comment by fsenf** [comment]
Sorry for the delay in response. Let's keep in mind that NaN pose a problem here. And indeed, I need to check why all my data are corrupted somehow ....

Thanks again with your contribution. I am now happy with it.

**Pull request merged**
