### PR TITLE
Runnable notebooks

### PR DESCRIPTION
**Pull request by squidy5**
Made branch 'devel' target of pull request

### CODE REVIEW

**Comment by squidy5** [comment]
> @rudegrass, thanks for your update.
> 
>     1. I would love to have the PR onto the `devel` branch
> 
>     2. in `notebooks/Changing_Project_Parameters.ipynb`, In [32]: crashes with
>        ```python
>        NameError: name 'input_channels' is not defined
>        ```
> 
>     3. in `notebooks/Training_a_new_classifier.ipynb, In [46]: crashes with
> 
> 
> ```python
> FileNotFoundError: [Errno 2] No such file or directory: '../classifiers/NewRandomForestClassifier/data/training_data'
> ```
> 
> Could you please check what happened?

To 2: typo in notebook, should work now

To 3: Can not reproduce. I am assuming the project could not be initialized at the specified position, resulting in the error when trying to access the project later.
I added an Error that is thrown when the project can not initialize correctly.

**Comment by fsenf** [comment]
Thanks, 1 + 2 are fixed now.

For comment 3: I still get the same error:

```ipython
In [5]: cc.run_training_pipeline(create_filelist = False)

Masked indices set!
sampling took 0.42929863929748535 seconds

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 cc.run_training_pipeline(create_filelist = False)

File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/cloud_classifier.py:140, in cloud_classifier.run_training_pipeline(self, verbose, create_filelist, evaluation, create_training_data)
    138 self.apply_mask(verbose = verbose)
    139 if(create_training_data):
--> 140     v,l = self.create_training_set(verbose = verbose)
    141 else: 
    142     v,l = self.load_training_set()

File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/cloud_classifier.py:309, in cloud_classifier.create_training_set(self, verbose)
    307 v,l = super().create_training_set()
    308 filename = os.path.join(self.project_path, "data", "training_data")
--> 309 self.save_training_set(v,l, filename)
    310 if (verbose):
    311     print("Training data created!")

File /tmp/testing-ctypytools/CTyPyTool/notebooks/../cloud_classifier/data_handler.py:331, in data_handler.save_training_set(self, vectors, labels, filename)
    316 def save_training_set(self, vectors, labels, filename):
    317     """
    318     Saves a set of training vectors and labels
    319 
   (...)
    329         The labels of the training set
    330     """
--> 331     dump([vectors, labels], filename)

File ~/.miniconda3/envs/python38/lib/python3.8/site-packages/joblib/numpy_pickle.py:481, in dump(value, filename, compress, protocol, cache_size)
    479         NumpyPickler(f, protocol=protocol).dump(value)
    480 elif is_filename:
--> 481     with open(filename, 'wb') as f:
    482         NumpyPickler(f, protocol=protocol).dump(value)
    483 else:

FileNotFoundError: [Errno 2] No such file or directory: '../classifiers/NewRandomForestClassifier/data/training_data'
```

I guess, an intermediate step is missing here, because the project internal structure is different:

```bash
CTyPyTool/classifiers> ls -1 NewRandomForestClassifier/
filelists
settings

CTyPyTool/classifiers> ls -1 ForestClassifier/
data
filelists
labels
settings
```

Did you create `data` and `labels` subdirs by hand? What happens if you create a completely new classifier?

**Comment by squidy5** [comment]
With the more detailed error-messages I could reproduce the error .Pushed a bugfix. Folders are now created automatically when needed - this is the intended behavior. The bug was masked by a locally different structure of the "defaults" folder, which is copied on project creation.

**Comment by fsenf** [comment]
Great! Now, it runs through smoothly...

I actually do not understand the argument with the default dir. If it comes from https://github.com/rudegrass/CTyPyTool/tree/runnable_notebooks/cloud_classifier/defaults then it just contains the `filelists`and the `settings` subdirs...

**Pull request merged**
